### ISSUE TITLE
Find collection of work emails

### ISSUE THREAD

**Issue by anna-deng** [anna-deng/daily-briefing#2]

**Comment by lommyti** [comment]
https://www.cs.cmu.edu/~enron/

**Comment by lommyti** [comment]
http://wstyler.ucsd.edu/enronsent.html

**Comment by lommyti** [comment]
http://www.cs.cmu.edu/~einat/datasets.html

**Comment by lommyti** [comment]
https://catalog.ldc.upenn.edu/LDC2015T03
